server:
  port: 9901
spring:
  application:
    name: multi-data-source
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      maxActive: 50
      minIdle: 5
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/ry-vue?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
    ds2:
      driver-class-name: org.postgresql.Driver
      initialSize: 5
      maxActive: 50
      minIdle: 5
      password: umesa
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:postgresql://192.168.0.22:5432/ume_zpms
      username: ume
